HERO_CHARACTER_NAME = "Герой"
HERO_WAS_INJURED_EVENT = "hero_took_damage"
HERO_FINISHED_EVENT = "hero_health_info"
HERO_MISSED_EVENT = "hero_missed"
HERO_MISSES_TURN_EVENT = "hero_misses_turn"
HERO_ATTACKS_EVENT = "hero_attacks"
HERO_DEFENDS_HIMSELF_EVENT = "hero_defends_himself"
HERO_DEACTIVATE_PROTECTED_FIELD_EVENT = "hero_deactivate_protected_field"

ROBOT_CHARACTER_NAME = "Робот"
ROBOT_WAS_INJURED_EVENT = "robot_took_damage"
ROBOT_FINISHED_EVENT = "robot_health_info"
ROBOT_MISSED_EVENT = "robot_missed"
ROBOT_MISSES_TURN_EVENT = "robot_misses_turn"
ROBOT_USE_HOMING_MISSILES_EVENT = "robot_use_homing_missiles"
ROBOT_USE_REGULAR_CARTRIDGES_EVENT = "robot_use_regular_cartridges"
ROBOT_JAMMED_EVENT = "robot_jammed"
